<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>83b08ff3-8a07-43c7-ae0d-f30bfef22545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-static']/div/div/div/div/div/div[2]/div/div/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.text-left > a.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d00eeadd-10e3-44dc-a1d8-5790ed0a7ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/campaigns/263</value>
      <webElementGuid>546c6fb0-e4ab-4a1f-9931-08953ce5b4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>bcda20ec-61b5-453f-8fa3-5a07742a6404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>エイベックス株式会社</value>
      <webElementGuid>bcf3c3f2-5d5b-432d-84e7-d9286f765cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-static&quot;)/div[@class=&quot;static-content-wrapper&quot;]/div[@class=&quot;static-content&quot;]/div[@class=&quot;page-content page-campaigns&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;panel panel-default ng-scope&quot;]/div[@class=&quot;panel-body p-md&quot;]/div[@class=&quot;table-responsive table-bordered mb-n&quot;]/div[@class=&quot;dataTables_wrapper form-inline no-footer&quot;]/table[@class=&quot;table table-bordered table-striped dataTable no-footer&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;text-left&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>8c984e0c-ac66-496b-be70-031990f0490a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-static']/div/div/div/div/div/div[2]/div/div/table/tbody/tr/td/a</value>
      <webElementGuid>5936f9d9-e048-4d4b-9ffb-5bf69d324f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'エイベックス株式会社')]</value>
      <webElementGuid>0e59b336-5270-41b6-aa47-f20166f3d258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channels'])[1]/following::a[1]</value>
      <webElementGuid>5def3dae-a972-43dc-874c-e16536802948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost (￥)'])[1]/following::a[1]</value>
      <webElementGuid>418432a7-e692-42c4-a62b-017a2fffc76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='running'])[1]/preceding::a[1]</value>
      <webElementGuid>fffc3b1f-2e37-4b48-b7be-69fd1ab00747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::a[1]</value>
      <webElementGuid>5fbb0f9e-978b-4420-95d4-40b2e205848a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='エイベックス株式会社']/parent::*</value>
      <webElementGuid>b9f681d9-2702-4c79-a93f-2ea2c81e505e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/campaigns/263')]</value>
      <webElementGuid>f0de577b-fc56-4630-8373-a25acf9a9e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>19d6e5cf-a2af-4df3-b7e4-113530e1de12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/campaigns/263' and (text() = 'エイベックス株式会社' or . = 'エイベックス株式会社')]</value>
      <webElementGuid>73c872b4-aa61-4cf0-bf6b-c22ac76432b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
