<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_New Record 2</name>
   <tag></tag>
   <elementGuidId>cfc323fa-2077-44bd-9647-70f6eaea16b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-static']/div/div/div/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.quick-jump-campaign.form-control.btn.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope.ng-not-empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b0b9c8d5-9c3c-411d-b21d-8d4b1b4c4106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quick-jump-campaign form-control btn ng-pristine ng-untouched ng-valid ng-isolate-scope ng-not-empty</value>
      <webElementGuid>bcc1d2f9-bdbf-4a5f-9834-16d954f10531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>campaign.id as campaign.name for campaign in followingCampaigns</value>
      <webElementGuid>94fe5541-f16e-43bf-885a-df95c476eef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>selectedCampaignId</value>
      <webElementGuid>0d288400-5e94-458e-be59-2a7cc50dbe36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>onSelectCampaign()</value>
      <webElementGuid>15874e34-5121-4d68-b9b2-b063676788df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Record 2株式会社ナノオプト・メディアエイベックス株式会社</value>
      <webElementGuid>56dca15a-dbd3-4bd2-8eff-e7d392f40b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-static&quot;)/div[@class=&quot;static-content-wrapper&quot;]/div[@class=&quot;static-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;row breadcrumb-has-filter&quot;]/div[@class=&quot;col-md-6 pr-n filter-wrapper form-group-sm&quot;]/select[@class=&quot;quick-jump-campaign form-control btn ng-pristine ng-untouched ng-valid ng-isolate-scope ng-not-empty&quot;]</value>
      <webElementGuid>67c65b24-d7b6-402c-b2e0-499892b4f2a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-static']/div/div/div/div/div/select</value>
      <webElementGuid>aa8da447-3b1a-4a8a-994d-26e024ad6f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Record 2'])[1]/following::select[1]</value>
      <webElementGuid>87a632b9-c9ed-472c-bc57-2d930efb81e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaigns'])[2]/following::select[1]</value>
      <webElementGuid>1ae7e20d-416c-4aca-80c1-c7bf70bce973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::select[2]</value>
      <webElementGuid>799b9e7b-d48d-4258-8c0f-bac777fdb7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0d985f27-9ce0-4118-b14c-7b29c24f4126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'New Record 2株式会社ナノオプト・メディアエイベックス株式会社' or . = 'New Record 2株式会社ナノオプト・メディアエイベックス株式会社')]</value>
      <webElementGuid>1ee06130-1eac-4517-9bb7-8e870c7f2057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
