<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Report_fa fa-angle-down</name>
   <tag></tag>
   <elementGuidId>eb7884ea-d27f-4a2c-b8dd-853f16ecfee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='horizontal-navbar']/ul/li[2]/a/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>31cb1d65-294f-4043-8c71-906ba107f678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-down</value>
      <webElementGuid>f5a0fd54-d0ee-42b3-ba08-165f7424c054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horizontal-navbar&quot;)/ul[@class=&quot;nav navbar-nav smart-menu&quot;]/li[@class=&quot;dropdown ng-scope active&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;ng-binding&quot;]/i[@class=&quot;fa fa-angle-down&quot;]</value>
      <webElementGuid>bf923ece-978f-4b63-b834-ae21c93fb901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5716dc8f-872c-418b-be33-21580b5b3e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-down</value>
      <webElementGuid>a7995ad2-1bb6-4a73-b947-1614bc8fd9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horizontal-navbar&quot;)/ul[@class=&quot;nav navbar-nav smart-menu&quot;]/li[@class=&quot;dropdown ng-scope&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;ng-binding&quot;]/i[@class=&quot;fa fa-angle-down&quot;]</value>
      <webElementGuid>492a6fe0-513e-4b77-8872-c8e4369bf020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='horizontal-navbar']/ul/li[2]/a/span/i</value>
      <webElementGuid>60fde1fd-c49b-4f5c-a1e7-182abee31ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a/span/i</value>
      <webElementGuid>4dfad21d-7360-4fdd-9d5e-c3f183e0c8a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
