<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Report</name>
   <tag></tag>
   <elementGuidId>fafaccb0-dca4-43fe-88c6-90ae5254824e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='horizontal-navbar']/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-toggle > span.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>71827f02-2d6b-4e05-8c39-daf0e6259958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>2a8f4c6f-37dc-4c1f-9081-83fd651ad22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Report </value>
      <webElementGuid>071255d9-163c-4279-8f1a-cfd09bb65462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horizontal-navbar&quot;)/ul[@class=&quot;nav navbar-nav smart-menu&quot;]/li[@class=&quot;dropdown ng-scope&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>919b7186-12e4-436d-9090-6e2389e88b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f482ecc9-3fbc-4a5f-af79-0d6729528797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>a3a90151-0fe0-403a-b42a-c128bbd30adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Report </value>
      <webElementGuid>654b40fb-85b9-40e4-b16e-f5e6e3bc26d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horizontal-navbar&quot;)/ul[@class=&quot;nav navbar-nav smart-menu&quot;]/li[@class=&quot;dropdown ng-scope active&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>da199d73-2e9b-4f5f-bf19-d709cad700cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='horizontal-navbar']/ul/li[2]/a/span</value>
      <webElementGuid>3b194dc6-77ed-4cc4-b184-8ec945fd9ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::span[1]</value>
      <webElementGuid>7bc5ad48-43f6-417e-9d62-2cc7b861dd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Japanese'])[1]/following::span[2]</value>
      <webElementGuid>386e1e37-63ca-41b6-a370-0cd85dac70de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCC'])[1]/preceding::span[1]</value>
      <webElementGuid>33fe0f7b-026c-4090-8104-9989e811abd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::span[1]</value>
      <webElementGuid>734bdb1b-43ab-4ead-baf0-c725d96e519e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Report']/parent::*</value>
      <webElementGuid>bebabe94-cba7-42b6-9632-8c2f8627e0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a/span</value>
      <webElementGuid>0244ff5a-5c81-4615-a184-5392cce34e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Report ' or . = 'Report ')]</value>
      <webElementGuid>c1f04ace-8475-4951-a0c6-11a952be1b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[1]/preceding::span[1]</value>
      <webElementGuid>4fbe97fb-56d1-4cb8-a187-3f8c32a844a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
