<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HYBRID_switchery</name>
   <tag></tag>
   <elementGuidId>f63600f3-d55e-4266-8af3-e3d97a9179be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-static']/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/table/tbody/tr[8]/td[3]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b03a7fe-1b8e-4243-af47-9e7154e9b2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switchery</value>
      <webElementGuid>ac03a20b-2198-46c1-9ab7-48671b8c3eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-static&quot;)/div[@class=&quot;static-content-wrapper&quot;]/div[@class=&quot;static-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;container-fluid ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body p-md&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/div[1]/div[1]/div[@class=&quot;table-responsive mb-md&quot;]/table[@class=&quot;table table-striped mb-n&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;text-center&quot;]/span[1]/span[@class=&quot;switchery&quot;]</value>
      <webElementGuid>a3580c76-fb71-4746-b118-141b0950256c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-static']/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/table/tbody/tr[8]/td[3]/span/span</value>
      <webElementGuid>0b43d19f-e2f2-4366-9487-200ff3f95621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HYBRID'])[3]/following::span[2]</value>
      <webElementGuid>6e898b01-12fb-4e58-a081-fbf988e60f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCC'])[1]/following::span[2]</value>
      <webElementGuid>06aa04a8-977d-4104-bbfb-b63bf176e82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Criteo'])[1]/preceding::span[2]</value>
      <webElementGuid>3f6a512f-627f-445e-b9ef-62cb5a3484ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HYBRID'])[4]/preceding::span[2]</value>
      <webElementGuid>2b7621d3-bc40-4a55-a2ab-27328513ec06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[3]/span/span</value>
      <webElementGuid>f6a843a1-aa80-43e4-81d7-afe69d7aed61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
